### PR TITLE
Fixed Non-deterministic behavior of HashMap that might fail tests using ContentFragment.getExportedElements()

### LINKED ISSUE #2608: [Content Fragment] Non-deterministic behavior of `HashMap` might fail tests using `ContentFragment.getExportedElements()`
## Bug Report

**Current Behavior**

- The `ContentFragmentImplTest` mocks JSON resources to `ContentFragment` objects through `ContentFragmentMockAdapter` at https://github.com/adobe/aem-core-wcm-components/blob/3524e33424bf6831faca014284c5bad803d3744d/bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/AbstractContentFragmentTest.java#L124-L125
https://github.com/adobe/aem-core-wcm-components/blob/3524e33424bf6831faca014284c5bad803d3744d/bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/AbstractContentFragmentTest.java#L170-L171
- The adapter mocks the `DAMContentElement`, which is part of `ContentFragment`, by loading the json resource at https://github.com/adobe/aem-core-wcm-components/blob/3524e33424bf6831faca014284c5bad803d3744d/bundles/core/src/test/java/com/adobe/cq/wcm/core/components/internal/models/v1/contentfragment/ContentFragmentMockAdapter.java#L109-L116
- During the translation of `JSON` to `MockElement` using `org.apache.sling` dependency (a detailed explanation is provided with screenshots in the last section), the ordering of the properties is lost because of `HashMap.entrySet()`. According to the [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html), `HashMap` is not guaranteed to maintain order over time.
- This might cause issues where the order is strictly enforced.
- Specifically, the following tests expects the order of `DAMContentFragment.getExportedElementsOrder()` to be `main` followed by `second`
 1) `com.adobe.cq.wcm.core.components.internal.models.v1.contentfragment.ContentFragmentImplTest.structured`
 2) `com.adobe.cq.wcm.core.components.internal.models.v1.contentfragment.ContentFragmentImplTest.structuredNonExistingVariation`
 3) `com.adobe.cq.wcm.core.components.internal.models.v1.contentfragment.ContentFragmentImplTest.structuredVariation`
 4) `com.adobe.cq.wcm.core.components.internal.servlets.contentfragment.ElementsDataSourceServletTest.testComponentPathStructured`
 5) `com.adobe.cq.wcm.core.components.internal.servlets.contentfragment.ElementsDataSourceServletTest.testFragmentPathOverride`
 6) `com.adobe.cq.wcm.core.components.internal.servlets.contentfragment.ElementsDataSourceServletTest.testFragmentPathStructured`

#### Steps to Reproduce 
- When the above tests are run through [NonDex](https://github.com/TestingResearchIllinois/NonDex), which shuffles the order of elements returned by `HashMap.keySet()`, we could observe the mentioned issue.
```
# Clone the Repo
https://github.com/adobe/aem-core-wcm-components.git

# Compile the module byte-buddy-dep
mvn clean install -pl bundles/core -am -DskipTests

# (Optional) Run the unit test
mvn -pl bundles/core test -Dtest=<Above Mentioned Test Name>

# Run the unit test using NonDex
mvn -pl bundles/core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=<Above Mentioned Test Name>
```
- Reproducing the above steps for Tests 1, 2, and 3, will produce the following result:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ContentFragmentImplTest.structured:137->assertContentFragment:283->assertContentFragment:311 Element has wrong name ==> expected: <main> but was: <second>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```
- Reproducing the above steps for Tests 4, 5, and 6 will produce the following result:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ElementsDataSourceServletTest.testComponentPathStructured:134->AbstractContentFragmentDataSourceServletTest.assertDataSource:127 expected: <main> but was: <second>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```

**Expected behavior/code**
- For any amount of runs, the order of `DAMContentFragment.getExportedElementsOrder()` should have been
  1) MAIN
  2) SECOND
- The test should have passed successfully without any errors with `NonDex`.

**Environment**
- Core Components version: `2.23.5-SNAPSHOT`
- Java version: `Java(TM) SE Runtime Environment (build 1.8.0_381-b09)`

**Possible Solution**

- Since the change in ordering of elements loaded by `resource.getChild()` when mocking the `ContentFragment` causes the issue, sorting the elements loaded by the resource will solve the issue. Sorting the elements based on the `resource.getValueMap().keySet()` ensures that the elements be returned in the order `MAIN` followed by `SECOND`.
- Below is the diff needed to solve the above mentioned issue.
```
-/+ com.adobe.cq.wcm.core.components.internal.models.v1.contentfragment.ContentFragmentMockAdapter.java | LineNo: 111
+    for (String name : master.getValueMap().keySet().stream().sorted().collect(Collectors.toList()))
-     for (String name : master.getValueMap().keySet())
```
- This change is made only in the `ContentFragmentMockAdapter.java` because the main issue results from incorrectly loading the test data.
- If the proposed solution looks good, I can create a PR.

**Additional context / Screenshots**

Here's an example scenario where the change in ordering occurs when run through `NonDex` for the test `com.adobe.cq.wcm.core.components.internal.models.v1.contentfragment.ContentFragmentImplTest.structured`. Since the issue occurs when loading the json resource for all the tests, the below scenario applies to all the tests.

1) The resource loaded will be specific for each test. However, one of the common files is `bundles/core/src/test/resources/contentfragment/test-content-dam-contentfragments.json`. This is the JSON from which the mocks are loaded and asserted.
Screenshot 2023-10-31 at 7 19 14 PM

2) The contents of the JSON are parsed recursively at apache sling's `JsonContentParser.java:87`.  The contents are loaded from the resource into `JsonObject`. This object uses `LinkedHashMap` to store the tree structure. So, the issue is not in the JsonObject. Looking in the below image, we could observe that `object.keySet()` gives the elements in the order of the above image. However, each json object is parsed to the resource contents by extracting the values to `properties` map, which in turn is a `HashMap`. The order of values in this `HashMap` might differ based on its implementation in a specific environment or java version.

Screenshot 2023-10-31 at 2 33 40 PM

Screenshot 2023-10-31 at 2 35 05 PM

3) While converting the values of the json to their respective resources, the `properties` map populated in the above imaged is passed to the `LoaderContentHandler.java:82`. Since this is a `HashMap`, `content.entrySet()` might return not return the same order for all the runs. This non-deterministic order map is provider to the `JcrResourceProvider`, which converts the json values to `JcrValueMap` used by the `ContentFragmentMockAdapter`

Screenshot 2023-10-31 at 2 37 40 PM

4) Accessing this map's key set at `ContentFragmentMockAdapter` gives the  following order
Screenshot 2023-10-31 at 2 40 38 PM

5) The mock elements created based on the above order of map is `MAIN` followed by `SECOND`
Screenshot 2023-10-31 at 2 55 18 PM

#### This is the second run for the same method run through `NonDex`.

1) The order of elements from the `JsonObject` remains constant because of `LinkedHashMap`
Screenshot 2023-10-31 at 2 43 57 PM

2) However, when the `properties` hash map is inserted, the change in order could be observed.
Screenshot 2023-10-31 at 2 44 30 PM

3) Creating the `JcrValueMap` based on this ordering
Screenshot 2023-10-31 at 2 46 21 PM

4) Accessing this map's key set at `ContentFragmentMockAdapter` gives a different order
Screenshot 2023-10-31 at 2 47 14 PM

5) The mock elements created based on the above order of map is `SECOND` followed by `MAIN`
Screenshot 2023-10-31 at 2 54 40 PM

### PR DESCRIPTION
**Pull request by saaivenk**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes [`#2608`](https://github.com/adobe/aem-core-wcm-components/issues/2608)
| Patch: Bug Fix?          | Yes
| Minor: New Feature?      | No
| Major: Breaking Change?  | No
| Tests Added + Pass?      | Tests Pass
| Documentation Provided   | No (Added Code Comments)
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

- Since the change in ordering of elements loaded by `resource.getChild()` when mocking the `ContentFragment` causes the issue, sorting the elements loaded by the resource will solve the issue. 
- Sorting the elements based on the property name ensures that the elements are always returned in a deterministic order.
- I have used `streams().sorted()` to sort the key set, and I have collected the values in `List` to make sure the order remains constant across different runs.

### CODE REVIEW

**Comment by RugvedB** [comment]
Ok, Noted. Feel free to let me know after you update the PR description. Thank you!

**Comment by njain2208** [comment]
Let us know when you have updated the title, branch, and description. The changes you have made look good to me.

**Comment by saaivenk** [comment]
@RugvedB @njain2208 I have updated the PR for your review. The necessary details are linked in the Fixed issues section.

**Comment by RugvedB** [comment]
I went through your code and it looks good to me. I just feel that the explanation is too lengthy but if thats not an issue, then its all good. Good work.

**Pull request merged**
